name: Terraform Deploy

on:
  workflow_dispatch: # Allows you to manually trigger the workflow

jobs:
  terraform:
    runs-on: ubuntu-latest
    environment: aws

    # Define environment variables at the job level
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION }}
      AWS_REGION: ${{ secrets.AWS_REGION }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    - name: Build, tag, and push db_updater image to Amazon ECR
      id: build-image
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY_NAME }}
        IMAGE_TAG: ${{ github.sha }}  # Use the commit SHA for unique tagging
      run: |
        cd db_updater
        cd app
        docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

    # Step: Set up Terraform
    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.3.0

    # Step: Terraform Init and Apply (Provisions EC2)
    - name: Initialize Terraform
      run: |
        cd terraform
        terraform init

    - name: Plan Terraform changes
      env:
        TF_VAR_aws_region: ${{ secrets.AWS_REGION }}
        TF_VAR_ec2_ssh_public_key: ${{ secrets.EC2_SSH_PUBLIC_KEY }}
      run: |
        cd terraform
        terraform plan -out=tfplan

    - name: Apply Terraform changes
      id: tf-apply
      run: |
        cd terraform
        terraform apply tfplan

    - name: Echo
      id: echo
      run: |
        echo "INSTANCE_PRIVATE_IP=$(terraform-bin output -raw ec2_private_ip)" >> $GITHUB_ENV
        echo "INSTANCE_PUBLIC_IP=$(terraform-bin output -raw ec2_public_ip)" >> $GITHUB_ENV
#        echo "output = ${ steps.tf-apply.outputs.ec2_private_ip }"
#        echo "output_V2 = ${ steps.tf-apply.outputs.ec2_public_ip }"

    # Step: Deploy Docker using Appleboy SSH Action (Direct Terraform Output)
    - name: Deploy Docker on EC2
      uses: appleboy/ssh-action@v0.1.10
      with:
#        host: ${{ env.INSTANCE_IP }}
        host: ${{ steps.tf-apply.outputs.ec2_private_ip }}
        username: ubuntu
        key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
        script: |
          sudo apt update -y
          sudo apt install -y docker.io
          sudo systemctl start docker
          
          # Login to Amazon ECR
          aws ecr get-login-password --region $AWS_REGION | sudo docker login --username AWS --password-stdin $ECR_REGISTRY
          
          # Pull and run the Docker container
          sudo docker pull $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          echo "done all"
